### ISSUE TITLE
能否列举下使用了哪些开源数据集和私有数据集？

### ISSUE THREAD

**Issue by CanvaChen** [UnicomAI/Unichat-llama3-Chinese#4]

**Comment by UnicomAI** [comment]
基本使用llamafactory自带的指令数据，中文

**Comment by UnicomAI** [comment]
> > 使用llamafactory自带的指令数据可以试试，自有不方便开源
> 
> @UnicomAI 您好，可能我没表达清楚，我这边不需要数据，只是想知道数据集名称而已。能否提供下训练时使用的开源数据集的名称，以及私有数据的类别名称？

私有都是自己的，看看llamafactory工程下自带的一些开源指令，我感觉也不错
